[server]
headless = true

[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#E0E0EF"
textColor = "#262730"
font = "sans serif"

[app]
title = "About FinCluster"
